version: '3.4.1'

services:
  app:
    build:
        context: .
        dockerfile: D:\DDownloads\TicketManagementSystem\TicketManagementSystem\dockerfile.txt

    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
